# Generated by Django 2.0 on 2018-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20181006_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
